---
application:
  name: "astrangerchatapp"
  project: "Akadbkad"
  organization: "QoveryCommunity"
routers:
- name: "main-astrangerchatapp"
  routes:
  - application_name: "astrangerchatapp"
    paths:
    - "/*"
